config/routes.rb
Rails.application.routes.draw do
  get 'about/info'
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :activity_logs, :activities

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :activity, required: false
  belongs_to :user, required: false
  validates :activity_id, presence: true
end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  before_action :authenticate_user!

  def index
    if user_signed_in?
      @activity_logs = ActivityLog.where(user_id: current_user.id)
    else
      nil
    end
  end

  def show
    @activity_log = ActivityLog.find(params[:id])
  end

  def new
    @activity_log = ActivityLog.new
  end

  def edit
    @activity_log = ActivityLog.find(params[:id])
  end

  def create
    @activity_log = ActivityLog.new(activity_log_params)
    @activity_log.user_id = current_user.id
    if @activity_log.save
      redirect_to @activity_log
    else
      render 'new'
    end
  end

  def update
    @activity_log = ActivityLog.find(params[:id])

    if @activity_log.update(activity_log_params)
      redirect_to @activity_log
    else
      render 'edit'
    end
  end

  def destroy
    @activity_log = ActivityLog.find(params[:id])
    @activity_log.destroy

    redirect_to activity_logs_path
  end


  private
    def activity_log_params
      params.require(:activity_log).permit(:date, :duration, :activity_id, :user_id)
    end
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/views/activity_logs/_form.html.erb
<%= form_with model: @activity_log, local: true do |form| %>

  <% if @activity_log.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@activity_log.errors.count, "error") %> prohibited
        this log from being saved:
      </h2>
      <ul>
        <% @activity_log.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label >Activity: </label>
    <%= form.collection_select :activity_id, Activity.order(:id),:id,:title, {prompt: true}, {class: 'form-control text-center'} %>
  </div>
  <div class="form-group">
    <label>Date: </label>
    <%= form.date_field :date, class: 'form-control datepicker text-center', value: "Date"%>
  </div>
  <div class="form-group">
    <label>Duration: </label>
    <%= form.number_field :duration, class: "form-control text-center", placeholder: "Minutes", type: "number", required: true %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-outline-dark form-control' %>
  </div>

<% end %>

app/views/activity_logs/edit.html.erb
<main class="flex-fill">
  <div class="container text-center border border-light p-5 w-25">
    <h1>Edit Activity Log</h1>

    <%= render 'form' %>

    <%= link_to 'Back', activity_logs_path, class: 'btn btn-dark m-3' %>
  </div>
</main>

app/views/activity_logs/index.html.erb
<main class="flex-fill">
  <div class="container text-center">  
    <h1 class="m-3">Your Activity Logs</h1>

    <%= link_to 'New log', new_activity_log_path, class: 'btn btn-outline-dark m-3' %>

    <div id="activity_log_table">
      <table class="table table-dark table-hover table-bordered">
        <thead>
            <tr>
              <th scope="col">Activity</th>
              <th scope="col">Date</th>
              <th scope="col">Duration</th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
      <% @activity_logs.each do |log| %>
        <tbody>
          <tr>
            <td th scope="row"><%= Activity.find(log.activity_id).title %></td>
            <td th scope="row"><%= log.date %></td>
            <td th scope="row"><%= log.duration %></td>
            <td th scope="row"><%= link_to 'Edit', edit_activity_log_path(log) %></td>
            <td th scope="row"><%= link_to 'Delete', activity_log_path(log),
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete this record?'} %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>
  </div>  
</main>

app/views/activity_logs/new.html.erb
<main class="flex-fill"> 
  <div class="container text-center border border-light p-5 w-25">
    <h1 class="m-3">New Log</h1>

    <%= render 'form' %>
  </div>
</main>

app/views/activity_logs/show.html.erb
<main class="flex-fill">  
  <div class="container text-center mt-5">
    <p>
      <strong>Activity:</strong>
    </p>


    <p>
      <strong>User:</strong>
      <%= User.find(@activity_log.user_id).email %>
    </p>
    <p>
      <strong>Date:</strong>
      <%= @activity_log.date %>
    </p>
    <p>
      <strong>Duration:</strong>
      <%= @activity_log.duration %>
    </p>
    <p>
      <strong>Activity:</strong>
      <%= Activity.find(@activity_log.activity_id).title %>
    </p>

    <%= link_to 'Back', activity_logs_path, class: 'btn btn-dark' %>
  <div class="container text-center">  
</main>