config/routes.rb
Rails.application.routes.draw do
  get 'about/info'
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :activity_logs, :activities

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_logs
  has_many :users, through: :activity_logs
  validates :title, presence: true,
                    length: { minimum: 2 }
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :activity, required: false
  belongs_to :user, required: false
  validates :activity_id, presence: true
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :activity_logs
  has_many :activities, through: :activity_logs
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def info
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]

 def index
   @activities = Activity.all
 end

 def show
   @activity = Activity.find(params[:id])
 end

 def new
   @activity = Activity.new
 end

 def edit
   @activity= Activity.find(params[:id])
 end

 def create
   @activity = Activity.new(activity_params)

   if @activity.save
     redirect_to @activity
   else
     render 'new'
   end
 end

 def update
   @activity = Activity.find(params[:id])

   if @activity.update(activity_params)
     redirect_to @activity
   else
     render 'edit'
   end
 end

 def destroy
   @activity = Activity.find(params[:id])
   @activity.destroy

   redirect_to activities_path
 end

 private
   def activity_params
       params.require(:activity).permit(:title)
   end

end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  before_action :authenticate_user!

  def index
    if user_signed_in?
      @activity_logs = ActivityLog.where(user_id: current_user.id)
    else
      nil
    end
  end

  def show
    @activity_log = ActivityLog.find(params[:id])
  end

  def new
    @activity_log = ActivityLog.new
  end

  def edit
    @activity_log = ActivityLog.find(params[:id])
  end

  def create
    @activity_log = ActivityLog.new(activity_log_params)
    @activity_log.user_id = current_user.id
    if @activity_log.save
      redirect_to @activity_log
    else
      render 'new'
    end
  end

  def update
    @activity_log = ActivityLog.find(params[:id])

    if @activity_log.update(activity_log_params)
      redirect_to @activity_log
    else
      render 'edit'
    end
  end

  def destroy
    @activity_log = ActivityLog.find(params[:id])
    @activity_log.destroy

    redirect_to activity_logs_path
  end


  private
    def activity_log_params
      params.require(:activity_log).permit(:date, :duration, :activity_id, :user_id)
    end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Move and Groove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column" style="min-height: 100vh">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand text-info" href="/">Move & Groove</a>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <a class="nav-link text-light" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="/activity_logs">Activity</a>
        </li>
        <li class="nav-item">
          <% if admin_signed_in? %>
            <a class="nav-link text-light" href="/activities/new">Add Activity</a>
          <% else %>
            <a class="nav-link text-light" href="/about/info"> About</a>
          <% end %>       
      </ul>  
      <div>
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
              <a class="nav-link text-light">Signed in as <%= current_user.email %></a>
          </li>
          <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <% else %>
              <%= link_to 'Register', new_user_registration_path, class: "nav-link text-light" %> 
          </li>
          <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: "nav-link text-light" %>
            <% end %>          
          </li>
        </ul>
      </div>   
    </div>    
  </nav>
    
    <%= yield %>
      <footer class="footer bg-dark">
        <div class="text-center py-3">
          <a class="text-white mx-3" href="/"> Home</a>
          <a class="text-white mx-3" href="/activity_logs"> Activity</a>
          <a class="text-white mx-3" href="/about/info"> About</a>
          <% if admin_signed_in? %>
            <a class="text-white mx-3" href="/activities">Add Activity</a>
          <% else %>
          <% end %> 
        </div>
        <div class="footer-copyright text-center py-3">
          <a class="text-white" href="https://www.ereich.eu">&copy 2020 Move & Groove</a>
        </div>
      </footer>
  </body>
</html>