config/routes.rb
Rails.application.routes.draw do
  get 'about/info'
  devise_for :admins
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'home/index'

  resources :activity_logs, :activities

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :activity_logs
  has_many :users, through: :activity_logs
  validates :title, presence: true,
                    length: { minimum: 2 }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]

 def index
   @activities = Activity.all
 end

 def show
   @activity = Activity.find(params[:id])
 end

 def new
   @activity = Activity.new
 end

 def edit
   @activity= Activity.find(params[:id])
 end

 def create
   @activity = Activity.new(activity_params)

   if @activity.save
     redirect_to @activity
   else
     render 'new'
   end
 end

 def update
   @activity = Activity.find(params[:id])

   if @activity.update(activity_params)
     redirect_to @activity
   else
     render 'edit'
   end
 end

 def destroy
   @activity = Activity.find(params[:id])
   @activity.destroy

   redirect_to activities_path
 end

 private
   def activity_params
       params.require(:activity).permit(:title)
   end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_with model: @activity, local: true do |form| %>

  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@activity.errors.count, "error") %> prohibited
        this Activity from being saved:
      </h2>
      <ul>
        <% @activity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, type: "text", required: true  %>
  </div>


  <p>
    <%= form.submit class: 'btn btn-outline-dark'%>
  </p>

<% end %>
  

app/views/activities/edit.html.erb
<main class="flex-fill">  
  <div class="container text-center">
    <h1>Edit Activity</h1>

    <%= render 'form' %>

    <%= link_to 'Back', activities_path, class: 'btn btn-primary' %>
  </div>  
</main>

app/views/activities/index.html.erb
<main class="flex-fill">
  <div class="container text-center">
    <h1 class="m-3">Activities</h1>

    <%= link_to 'New Activity', new_activity_path, class: 'btn btn-outline-dark m-3' %>

    <div>
      <table class="table table-striped table-bordered">
        <thead class="thead-dark">
        <tr>
          <th>Title</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>

        <% @activities.each do |activity| %>
          <tr>
            <td><%= activity.title %></td>
            <td><%= link_to 'Show', activity_path(activity) %></td>
            <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
            <td><%= link_to 'Delete', activity_path(activity),
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete ' + activity.title + '?' } %></td>
          </tr>
        <% end %>
      </table>
    </div>  
  </div>  
</main>

app/views/activities/new.html.erb
<main class="flex-fill">
  <div class="container text-center">
    <h1 class="m-3">New Activity</h1>

    <%= render 'form' %>

    <%= link_to 'Back', activities_path, class: 'btn btn-primary' %>
  </div>  
</main>

app/views/activities/show.html.erb
<main class="flex-fill">
  <div class="container text-center">
    <p>
      <h1><%= @activity.title %></h1>
    </p>

    <%= link_to 'Edit', edit_activity_path(@activity), :class => "btn btn-dark"%>
    <%= link_to 'Back', activities_path, :class => "btn btn-dark"%>
  </div>  
</main>